name: CI
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build pdf
        run: |
          sudo apt-get install texlive texlive-latex-recommended texlive-latex-extra texlive-bibtex-extra texlive-pictures latexmk -qq > /dev/null
          latexmk --pdf main.tex
